// https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/#available-scopes

const READ_ONLY_SCOPE = 'READ_ONLY_SCOPE';
const REPOSITORY_SCOPE = Object.freeze({
  COMMIT_STATUS: 'REPOSITORY_SCOPE_COMMIT_STATUS',
  DEPLOYMENT_STATUS: 'REPOSITORY_SCOPE_DEPLOYMENT_STATUS',
  PUBLIC_REPOSITORY: 'REPOSITORY_SCOPE_PUBLIC_REPOSITORY',
  INVITE_COLLABORATORS: 'REPOSITORY_SCOPE_INVITE_COLLABORATORS',
  EVERYTHING: 'REPOSITORY_SCOPE_FULL_ACCESS',
});

const ORGANIZATION_SCOPE = Object.freeze({
  READ_AND_WRITE: 'ORGANIZATION_SCOPE_READ_AND_WRITE_ACCESS',
  READ: 'ORGANIZATION_SCOPE_READ_ACCESS',
  EVERYTHING: 'ORGANIZATION_SCOPE_FULL_ACCESS',
});

const PUBLIC_KEY_SCOPE = Object.freeze({
  WRITE: 'PUBLIC_KEY_SCOPE_WRITE_ACCESS',
  READ: 'PUBLIC_KEY_SCOPE_READ_ACCESS',
  EVERYTHING: 'PUBLIC_KEY_SCOPE_FULL_ACCESS',
});

const REPOSITORY_HOOK_SCOPE = Object.freeze({
  WRITE: 'REPOSITORY_HOOK_SCOPE_WRITE_ACCESS',
  READ: 'REPOSITORY_HOOK_SCOPE_READ_ACCESS',
  EVERYTHING: 'REPOSITORY_HOOK_SCOPE_FULL_ACCESS',
});

const GIST_SCOPE = 'GIST_SCOPE';
const NOTIFICATIONS_SCOPE = 'NOTIFICATIONS_SCOPE';
const USER_SCOPE = Object.freeze({
  READ_USER_PROFILE: 'USER_SCOPE_READ_PROFILE_ACCESS',
  READ_EMAIL_ADDRESS: 'USER_SCOPE_READ_EMAIL_ADDRESS',
  FOLLOW: 'USER_SCOPE_FOLLOW',
  EVERYTHING: 'USER_SCOPE_FULL_ACCESS',
});

const DELETE_REPOSITORY_SCOPE = 'DELETE_REPOSITORY_SCOPE';
const DISCUSSION_SCOPE = Object.freeze({
  READ_AND_WRITE: 'DISCUSSION_SCOPE_READ_AND_WRITE_ACCESS',
  READ: 'DISCUSSION_SCOPE_READ_ACCESS',
  EVERYTHING: 'DISCUSSION_SCOPE_FULL_ACCESS',
});

const GPG_KEY_SCOPE = Object.freeze({
  WRITE: 'GPG_KEY_SCOPE_WRITE_ACCESS',
  READ: 'GPG_KEY_SCOPE_READ_ACCESS',
  EVERYTHING: 'GPG_KEY_SCOPE_FULL_ACCESS',
});

const SCOPES = Object.freeze({
  REPOSITORY: REPOSITORY_SCOPE,
  ORGANIZATION: ORGANIZATION_SCOPE,
  PUBLIC_KEY: PUBLIC_KEY_SCOPE,
  REPOSITORY_HOOK: REPOSITORY_HOOK_SCOPE,
  GIST: GIST_SCOPE,
  NOTIFICATIONS: NOTIFICATIONS_SCOPE,
  USER: USER_SCOPE,
  DELETE_REPOSITORY: DELETE_REPOSITORY_SCOPE,
  DISCUSSION: DISCUSSION_SCOPE,
  GPG_KEY: GPG_KEY_SCOPE,
});

export {
  READ_ONLY_SCOPE,
  REPOSITORY_SCOPE,
  ORGANIZATION_SCOPE,
  PUBLIC_KEY_SCOPE,
  REPOSITORY_HOOK_SCOPE,
  GIST_SCOPE,
  NOTIFICATIONS_SCOPE,
  USER_SCOPE,
  DELETE_REPOSITORY_SCOPE,
  DISCUSSION_SCOPE,
  GPG_KEY_SCOPE,
  SCOPES,
};
